import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { UserAuthButton } from "@/components/auth/user-auth-button";
import ThemeToggle from "@/components/app/ThemeToggle";
import { Navigation } from "@/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "张舟辰",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
            <div className="container flex h-14 items-center justify-between">
              <div className="flex items-center">
                <h1 className="text-xl font-bold mr-6">张舟辰</h1>
                <Navigation />
              </div>
              <div className="flex items-center space-x-4">
                <ThemeToggle />
                <UserAuthButton />
              </div>
            </div>
          </header>
          <main className="min-h-screen">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
